### ISSUE TITLE
Landing page: Tại sao phải cần có margin left?

### ISSUE THREAD

**Issue by nguyenduchuy271197** [nguyenduchuy271197/likelion-bootcamp#2]
Project: Làm một trang landing page
	- Make a responsive website (mobile-first)
	- Smooth scrolling
	- Thêm favicon và meta description
	- Tối ưu hình ảnh (Image Optimization) với Sqooush
	- Deploy trên Netlify

```css
body {
	margin:0;
	padding:0;
}
```
